# Generated by Django 6.0.6 on 2026-07-05 15:27

import books.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('name', models.CharField(help_text='Unique name of the category.', max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this category encompasses.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL-friendly slug for the category.', max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('name', models.CharField(help_text='Unique tag word or phrase.', max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(help_text='URL-friendly slug for the tag.', max_length=60, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('first_name', models.CharField(help_text="Author's first name.", max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Author's last name.", max_length=150, verbose_name='Last Name')),
                ('biography', models.TextField(blank=True, help_text='Brief biography or history of the author.', verbose_name='Biography')),
                ('country', models.CharField(blank=True, help_text='Country where the author is from.', max_length=100, verbose_name='Country of Origin')),
                ('date_of_birth', models.DateField(blank=True, help_text="Author's date of birth.", null=True, validators=[books.models.validate_past_date], verbose_name='Date of Birth')),
                ('website', models.URLField(blank=True, help_text='Official website of the author.', null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this author should be treated as active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='books_autho_last_na_7ca250_idx')],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('name', models.CharField(help_text='Unique name of the publishing company.', max_length=255, unique=True, verbose_name='Publisher Name')),
                ('address', models.TextField(blank=True, help_text='Physical or billing address of the publisher.', verbose_name='Address')),
                ('website', models.URLField(blank=True, help_text="Publisher's website.", null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='Contact email of the publisher.', max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=30, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this publisher is active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='books_publi_name_450a32_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('isbn', models.CharField(help_text='Unique 10 or 13-digit International Standard Book Number.', max_length=20, unique=True, validators=[books.models.validate_isbn], verbose_name='ISBN')),
                ('title', models.CharField(db_index=True, help_text='Main title of the book.', max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Sub-title of the book (if any).', max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, help_text='Detailed summary or synopsis of the book.', verbose_name='Description')),
                ('publication_year', models.IntegerField(help_text='Year the book was published.', validators=[books.models.validate_publication_year], verbose_name='Publication Year')),
                ('edition', models.CharField(blank=True, help_text="Edition info (e.g. '1st Edition', 'Revised').", max_length=50, verbose_name='Edition')),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('AR', 'Arabic'), ('HI', 'Hindi'), ('OTHER', 'Other')], default='EN', help_text='Primary language of the book.', max_length=10, verbose_name='Language')),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Total number of pages.', null=True, verbose_name='Pages')),
                ('cover_image', models.ImageField(blank=True, help_text='Uploaded cover artwork of the book.', null=True, upload_to='book_covers/', verbose_name='Cover Image')),
                ('total_copies', models.PositiveIntegerField(default=1, help_text='Total physical copies owned by the library.', verbose_name='Total Copies')),
                ('available_copies', models.PositiveIntegerField(default=1, help_text='Copies currently on shelf and available for borrowing.', verbose_name='Available Copies')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='User rating score from 0.00 to 5.00.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Rating')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', help_text='Current overall status of the book.', max_length=20, verbose_name='Status')),
                ('shelf_location', models.CharField(blank=True, help_text="Physical location coordinates in the library (e.g. 'Aisle 3, Shelf B').", max_length=100, verbose_name='Shelf Location')),
                ('authors', models.ManyToManyField(help_text='Authors who wrote the book.', related_name='books', to='books.author', verbose_name='Authors')),
                ('categories', models.ManyToManyField(help_text='Categories under which this book is classified.', related_name='books', to='books.category', verbose_name='Categories')),
                ('publisher', models.ForeignKey(help_text='Company that published the book.', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.publisher', verbose_name='Publisher')),
                ('tags', models.ManyToManyField(help_text='Descriptive tags used for recommendation engine indexing.', related_name='books', to='books.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'), models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['status'], name='books_book_status_ea5e47_idx')],
            },
        ),
    ]
