# Generated by Django 6.0.6 on 2026-07-05 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_memberprofile_role'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the book was borrowed.', verbose_name='Borrow Date')),
                ('due_date', models.DateTimeField(help_text='Date and time by which the book must be returned.', verbose_name='Due Date')),
                ('return_date', models.DateTimeField(blank=True, help_text='Date and time when the book was actually returned.', null=True, verbose_name='Return Date')),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='BORROWED', help_text='Current status of this borrow record.', max_length=20, verbose_name='Status')),
                ('renew_count', models.PositiveIntegerField(default=0, help_text='Number of times this borrow has been renewed (max 2).', verbose_name='Renewal Count')),
                ('remarks', models.TextField(blank=True, help_text='Optional notes about this borrow transaction.', verbose_name='Remarks')),
                ('book', models.ForeignKey(help_text='The book that was borrowed.', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='Book')),
                ('member', models.ForeignKey(help_text='The library member who borrowed the book.', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='accounts.memberprofile', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Borrow Record',
                'verbose_name_plural': 'Borrow Records',
                'ordering': ['-borrow_date'],
                'indexes': [models.Index(fields=['status'], name='borrow_borr_status_c90689_idx'), models.Index(fields=['due_date'], name='borrow_borr_due_dat_a372cc_idx'), models.Index(fields=['member', 'book', 'status'], name='borrow_borr_member__0d99e1_idx')],
            },
        ),
    ]
