# Generated by Django 6.0.6 on 2026-07-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile_role'),
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated fine amount in ₹.', max_digits=8, verbose_name='Fine Amount')),
                ('reason', models.CharField(default='Overdue book return fine.', help_text='Reason for the fine.', max_length=255, verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', help_text='Fine status (Pending, Paid, Waived).', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date and time when the fine was paid or waived.', null=True, verbose_name='Paid/Waived At')),
                ('borrow_record', models.OneToOneField(help_text='The associated borrow transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='borrow.borrowrecord', verbose_name='Borrow Record')),
                ('member', models.ForeignKey(help_text='The member who incurred the fine.', on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='accounts.memberprofile', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'ordering': ['-created_at'],
            },
        ),
    ]
