# Generated by Django 6.0.6 on 2026-07-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('membership_id', models.CharField(help_text='Unique library membership identification code.', max_length=50, unique=True, verbose_name='Membership ID')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, help_text='Academic or administrative department (e.g. Computer Science).', max_length=100, verbose_name='Department')),
                ('membership_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', help_text='The tier/type of library membership.', max_length=20, verbose_name='Membership Type')),
                ('borrow_limit', models.PositiveIntegerField(default=5, help_text='Maximum number of books this user can borrow concurrently.', verbose_name='Borrow Limit')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this member profile is active.', verbose_name='Is Active')),
                ('user', models.OneToOneField(help_text='The associated Django User account.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
