# Generated by Django 6.0.6 on 2026-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('LIBRARIAN', 'Librarian')], default='MEMBER', help_text='The role of this user (Member or Librarian).', max_length=20, verbose_name='User Role'),
        ),
    ]
