# Generated by Django 6.0.6 on 2026-07-13 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('short_ai_summary', models.TextField(blank=True, help_text='Short summary generated by AI.', verbose_name='Short AI Summary')),
                ('long_ai_summary', models.TextField(blank=True, help_text='Long summary generated by AI.', verbose_name='Long AI Summary')),
                ('recommendation_reason', models.TextField(blank=True, help_text='Reason for recommending this book.', verbose_name='Recommendation Reason')),
                ('search_text', models.TextField(blank=True, help_text='Text optimized for chatbot search indexing.', verbose_name='Search Text')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_metadata', to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Chatbot Metadata',
                'verbose_name_plural': 'Chatbot Metadata',
            },
        ),
    ]
