from django.db import models
import uuid
from django.contrib.auth.models import User
from core.models import BaseModel
from books.models import Book

class ChatbotMetadata(BaseModel):
    book = models.OneToOneField(
        Book,
        on_delete=models.CASCADE,
        related_name="chatbot_metadata",
        verbose_name="Book"
    )
    short_ai_summary = models.TextField(
        blank=True,
        verbose_name="Short AI Summary",
        help_text="Short summary generated by AI."
    )
    long_ai_summary = models.TextField(
        blank=True,
        verbose_name="Long AI Summary",
        help_text="Long summary generated by AI."
    )
    recommendation_reason = models.TextField(
        blank=True,
        verbose_name="Recommendation Reason",
        help_text="Reason for recommending this book."
    )
    search_text = models.TextField(
        blank=True,
        verbose_name="Search Text",
        help_text="Text optimized for chatbot search indexing."
    )

    class Meta:
        verbose_name = "Chatbot Metadata"
        verbose_name_plural = "Chatbot Metadata"

    def __str__(self) -> str:
        return f"Chatbot Metadata for {self.book.title}"


class ChatSession(BaseModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="chat_sessions",
        verbose_name="User"
    )
    session_id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        verbose_name="Session ID"
    )
    title = models.CharField(
        max_length=255,
        blank=True,
        verbose_name="Title"
    )

    class Meta:
        verbose_name = "Chat Session"
        verbose_name_plural = "Chat Sessions"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.user.username} - {self.title or str(self.session_id)}"


class ChatMessage(BaseModel):
    class SenderRole(models.TextChoices):
        USER = "user", "User"
        ASSISTANT = "assistant", "Assistant"

    session = models.ForeignKey(
        ChatSession,
        on_delete=models.CASCADE,
        related_name="messages",
        verbose_name="Session"
    )
    sender = models.CharField(
        max_length=20,
        choices=SenderRole.choices,
        verbose_name="Sender"
    )
    content = models.TextField(
        verbose_name="Content"
    )

    class Meta:
        verbose_name = "Chat Message"
        verbose_name_plural = "Chat Messages"
        ordering = ["created_at"]

    def __str__(self) -> str:
        return f"{self.sender}: {self.content[:50]}"

