# Generated by Django 6.0.6 on 2026-07-05 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_memberprofile_role'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the reservation request was placed.', verbose_name='Reservation Date')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='48-hour pickup window once status transitions to ACTIVE.', null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='WAITING', help_text='Current lifecycle state of the reservation.', max_length=20, verbose_name='Status')),
                ('queue_position', models.PositiveIntegerField(default=1, help_text='Queue position in waiting list for this book.', verbose_name='Queue Position')),
                ('remarks', models.TextField(blank=True, help_text='Optional comments or notes.', verbose_name='Remarks')),
                ('book', models.ForeignKey(help_text='The book being reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book', verbose_name='Book')),
                ('member', models.ForeignKey(help_text='The member making this reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.memberprofile', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['queue_position', 'reservation_date'],
                'indexes': [models.Index(fields=['status'], name='reservation_status_f1a03a_idx'), models.Index(fields=['queue_position'], name='reservation_queue_p_ed1ba6_idx'), models.Index(fields=['book', 'status'], name='reservation_book_id_d8fb3e_idx')],
            },
        ),
    ]
