# Generated by Django 6.0.6 on 2026-07-13 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('mood', models.CharField(blank=True, help_text='Mood tags separated by semicolons.', max_length=500, verbose_name='Mood')),
                ('writing_style', models.CharField(blank=True, help_text='Writing styles separated by semicolons.', max_length=500, verbose_name='Writing Style')),
                ('difficulty_level', models.CharField(blank=True, max_length=100, verbose_name='Difficulty Level')),
                ('reading_level', models.CharField(blank=True, max_length=100, verbose_name='Reading Level')),
                ('target_audience', models.CharField(blank=True, max_length=255, verbose_name='Target Audience')),
                ('learning_outcomes', models.CharField(blank=True, max_length=500, verbose_name='Learning Outcomes')),
                ('skills_covered', models.CharField(blank=True, max_length=500, verbose_name='Skills Covered')),
                ('recommendation_keywords', models.TextField(blank=True, verbose_name='Recommendation Keywords')),
                ('fantasy_elements', models.CharField(blank=True, max_length=500, verbose_name='Fantasy Elements')),
                ('scifi_elements', models.CharField(blank=True, max_length=500, verbose_name='Sci-Fi Elements')),
                ('themes', models.TextField(blank=True, verbose_name='Themes')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('tags', models.TextField(blank=True, verbose_name='Tags')),
                ('subjects', models.TextField(blank=True, verbose_name='Subjects')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_metadata', to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Recommendation Metadata',
                'verbose_name_plural': 'Recommendation Metadata',
            },
        ),
        migrations.CreateModel(
            name='SimilarBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('similarity_score', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Similarity Score')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_books_source', to='books.book', verbose_name='Source Book')),
                ('similar_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_books_target', to='books.book', verbose_name='Similar Book')),
            ],
            options={
                'verbose_name': 'Similar Book',
                'verbose_name_plural': 'Similar Books',
                'ordering': ['book', 'rank'],
                'unique_together': {('book', 'similar_book')},
            },
        ),
    ]
